package com.adina.objects;
// Generated Jun 16, 2010 7:13:39 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Functie generated by hbm2java
 */
public class Functie  implements java.io.Serializable {


     private Long idFunctie;
     private String numeFunctie;
     private Set angajats = new HashSet(0);

    public Functie() {
    }

	
    public Functie(String numeFunctie) {
        this.numeFunctie = numeFunctie;
    }
    public Functie(String numeFunctie, Set angajats) {
       this.numeFunctie = numeFunctie;
       this.angajats = angajats;
    }
   
    public Long getIdFunctie() {
        return this.idFunctie;
    }
    
    public void setIdFunctie(Long idFunctie) {
        this.idFunctie = idFunctie;
    }
    public String getNumeFunctie() {
        return this.numeFunctie;
    }
    
    public void setNumeFunctie(String numeFunctie) {
        this.numeFunctie = numeFunctie;
    }
    public Set getAngajats() {
        return this.angajats;
    }
    
    public void setAngajats(Set angajats) {
        this.angajats = angajats;
    }




}


