package com.adina.objects;
// Generated Jun 16, 2010 7:13:39 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Abilitate generated by hbm2java
 */
public class Abilitate  implements java.io.Serializable {


     private Long idAbilitate;
     private String numeAbilitate;
     private Set angajatAbilitates = new HashSet(0);

    public Abilitate() {
    }

	
    public Abilitate(String numeAbilitate) {
        this.numeAbilitate = numeAbilitate;
    }
    public Abilitate(String numeAbilitate, Set angajatAbilitates) {
       this.numeAbilitate = numeAbilitate;
       this.angajatAbilitates = angajatAbilitates;
    }
   
    public Long getIdAbilitate() {
        return this.idAbilitate;
    }
    
    public void setIdAbilitate(Long idAbilitate) {
        this.idAbilitate = idAbilitate;
    }
    public String getNumeAbilitate() {
        return this.numeAbilitate;
    }
    
    public void setNumeAbilitate(String numeAbilitate) {
        this.numeAbilitate = numeAbilitate;
    }
    public Set getAngajatAbilitates() {
        return this.angajatAbilitates;
    }
    
    public void setAngajatAbilitates(Set angajatAbilitates) {
        this.angajatAbilitates = angajatAbilitates;
    }




}


